// ======================================================================
/*!
 * \brief Manage access to the repository
 */
// ======================================================================

#pragma once

#include "RadarCatalog.h"
#include "Repository.h"
#include <boost/atomic.hpp>
#include <boost/thread.hpp>
#include <macgyver/AsyncTaskGroup.h>
#include <macgyver/Cache.h>
#include <macgyver/DirectoryMonitor.h>
#include <spine/Thread.h>
#include <filesystem>
#include <map>
#include <memory>
#include <mutex>
#include <set>

namespace SmartMet
{
namespace Engine
{
namespace Querydata
{
// Collection of files
using Files = std::vector<std::filesystem::path>;

struct RepoManager
{
  // construction & destruction

  ~RepoManager();
  explicit RepoManager(const std::string& configfile);

  RepoManager() = delete;
  RepoManager(const RepoManager& other) = delete;
  RepoManager& operator=(const RepoManager& other) = delete;
  RepoManager(RepoManager&& other) = delete;
  RepoManager& operator=(RepoManager&& other) = delete;

  // generic API

  const ProducerConfig& producerConfig(const Producer& producer) const;

  // callback requests

  void update(Fmi::DirectoryMonitor::Watcher id,
              const std::filesystem::path& dir,
              const boost::regex& pattern,
              const Fmi::DirectoryMonitor::Status& status);

  void error(Fmi::DirectoryMonitor::Watcher id,
             const std::filesystem::path& dir,
             const boost::regex& pattern,
             const std::string& message);

  void init();
  bool ready() const;
  void shutdown();

  // Reconcile the radar scratch cache against the sources and the size budget.
  // Called once per process before init() starts scanning: removes crash residue
  // (dot-prefixed temps, .trash), drops stale/rotated frames and de-configured
  // sources, keeps still-current frames for a warm restart, and enforces the
  // radar.cache_size budget (group-LRU eviction of whole sources). Not for a
  // config hot-reload, where the previous RepoManager still owns live scratch.
  void reconcileRadarCache() const;

  // Ensure a lazy producer's servable window is decoded and in the repository,
  // decoding it on first access if necessary. A no-op for non-lazy producers and
  // for lazy producers already loaded. Safe to call from request threads; it does
  // its own locking and must be called before taking itsMutex for a get().
  void ensureLoaded(const Producer& producer);

  // data members

  mutable Spine::MutexType itsMutex;  // mutexes should always be mutable
  libconfig::Config itsConfig;
  bool itsVerbose;

  Fmi::DirectoryMonitor itsMonitor;
  boost::thread itsMonitorThread;
  boost::thread itsExpirationThread;
  std::unique_ptr<Fmi::AsyncTaskGroup> updateTasks;

  // info on producers generated by constructor

  using ProducerConfigList = std::list<ProducerConfig>;
  ProducerConfigList itsConfigList;

  // available producers

  ProducerList itsProducerList;

  // watchers and the respective producer

  using ProducerMap = std::map<Fmi::DirectoryMonitor::Watcher, Producer>;
  ProducerMap itsProducerMap;

  // loaded data, updated regularly

  Repository itsRepo;

  // Cheap header-only metadata of every frame of each lazy radar producer, so
  // GetCapabilities can advertise the full time dimension without decoding. The
  // pixel decode is deferred to on-access (see RadarCatalog).
  RadarCatalog itsRadarCatalog;

  std::time_t configModTime;  // Timestamp of configuration file loaded
  std::time_t getConfigModTime() const { return configModTime; }

  void setOldManager(std::shared_ptr<RepoManager> oldmanager);
  void removeOldManager();

  Fmi::Cache::CacheStats getCacheStats() const { return itsLatLonCache.statistics(); }

 private:
  void load(Producer producer, Files files);
  // Core of load(): decode the given files into models and add them to the repo.
  // Shared by the directory-monitor path and by on-access lazy loading; does not
  // touch itsThreadCount (the caller owns it).
  void loadModels(const Producer& producer, const Files& files, const ProducerConfig& conf);
  void expirationLoop();

  bool producerHasModels(const Producer& producer) const;
  std::shared_ptr<std::mutex> lazyLoadMutex(const Producer& producer);

  Fmi::DirectoryMonitor::Watcher id(const Producer& producer) const;

  int itsMaxThreadCount;

  // Producers configured lazy (radar). Checked on every get() via ensureLoaded,
  // so kept as a fast set to avoid a config scan for the non-lazy common case.
  std::set<Producer> itsLazyProducers;
  // Per-producer locks serialising concurrent first-access decodes.
  std::mutex itsLazyLoadMapMutex;
  std::map<Producer, std::shared_ptr<std::mutex>> itsLazyLoadMutexes;

  // Directory for decoded radar scratch .sqd files (GeoTIFF/ODIM producers).
  // Should live on a real disk volume so the kernel page cache manages the
  // memory-mapped decoded frames. Overridable via config key
  // radar.scratch_directory; default below.
  std::filesystem::path itsRadarScratchDir{"/var/tmp/smartmet-qengine-radar"};

  // Total byte budget for the radar scratch cache; 0 = unlimited. Overridable
  // via config key radar.cache_size. When exceeded, whole least-recently-accessed
  // sources (producer subdirectories) are evicted (see RadarCache).
  std::uintmax_t itsRadarCacheBytes{0};

  boost::atomic<int> itsThreadCount;

  using LatLonCache = Fmi::Cache::Cache<std::size_t, std::shared_ptr<std::vector<NFmiPoint>>>;
  LatLonCache itsLatLonCache;

  std::shared_ptr<RepoManager> itsOldRepoManager;
};

}  // namespace Querydata
}  // namespace Engine
}  // namespace SmartMet

// ======================================================================
